import React from 'react';
import type { NextPage } from 'next';
import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import PageHero from 'components/blocks/PageHero';

import PostsList from 'components/posts/PostsList';
import useTranslation from 'hooks/useTranslation';
import { Box } from '@chakra-ui/react';
import theme, { containerProps } from 'styles/theme';

const BlogPage: NextPage = () => {
  const { t } = useTranslation('blog');

  return (
    <>
      <Head>
        <title>Mehdi Amrane | Fullstack JavaScript Developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box bgColor='white' mb={20} mt={16} w='full' as='main'>
        <Box
          bgImage={`linear-gradient(to bottom, ${theme.colors.white}, ${theme.colors.gray[200]})`}
          borderBottom='2px solid'
          borderColor='gray.300'
        >
          <PageHero
            title={t('blog.title')}
            subtitle={t('blog.subtitle')}
            description={t('blog.description')}
            image={{ src: '/images/pencil.png', alt: 'Pencil Illustration' }}
          />
        </Box>

        <Box {...containerProps} pt={{ base: 16, md: 20 }}>
          <PostsList />
        </Box>
      </Box>
    </>
  );
};

export default BlogPage;

export const getStaticProps: GetStaticProps = async ({ locale = 'en' }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'home', 'blog'])),
    },
  };
};
