import React from 'react';
import type { NextPage } from 'next';
import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import PageHero from 'components/blocks/PageHero';
import s from 'styles/pages/BlogPage.module.scss';
import PostsList from 'components/posts/PostsList';
import useTranslation from 'hooks/useTranslation';

const BlogPage: NextPage = () => {
  const { t } = useTranslation('blog');

  return (
    <>
      <Head>
        <title>Mehdi Amrane | Fullstack JavaScript Developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={s.blogpage}>
        <div className={s.blogpage__hero}>
          <PageHero
            title={t('blog.title')}
            subtitle={t('blog.subtitle')}
            description={t('blog.description')}
            image={{ src: '/images/pencil.png', alt: 'Pencil Illustration' }}
          />
        </div>

        <div className={s.blogpage__posts}>
          <PostsList />
        </div>
      </main>
    </>
  );
};

export default BlogPage;

export const getStaticProps: GetStaticProps = async ({ locale = 'en' }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'home'])),
    },
  };
};
