import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
// import useTranslation from 'hooks/useTranslation';

const Page404: NextPage = () => {
  // const { t } = useTranslation('about');

  return (
    <div>
      <Head>
        <title>404</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>404 error</h1>
    </div>
  );
};

export default Page404;

export const getStaticProps: GetStaticProps = async ({ locale = 'en' }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['about', 'common'])),
    },
  };
};
