import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import useTranslation from 'hooks/useTranslation';
import SectionTitle from 'components/blocks/SectionTitle';

const About: NextPage = () => {
  const { t } = useTranslation('about');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>{t('hello')}</h1>

      <SectionTitle title='salut' subtitle='salut' />
    </div>
  );
};

export default About;

export const getStaticProps: GetStaticProps = async ({ locale = 'en' }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['about', 'common'])),
    },
  };
};
