import React from 'react';
import type { NextPage } from 'next';
import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import Row from 'components/layout/Row';
import { useColorModeValue as mode } from '@chakra-ui/react';
import HomepageHero from 'components/blocks/HomepageHero';
import ContactSection from 'components/blocks/ContactSection';

const Homepage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mehdi Amrane | Fullstack JavaScript Developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Row
        py={{ base: 20, md: 28 }}
        bgGradient={mode('linear(to-b, white, gray.200)', 'linear(to-b, dark.900, dark.800)')}
        borderBottom='2px solid'
        borderColor={mode('gray.300', 'dark.600')}
      >
        <HomepageHero />
      </Row>

      <Row py={{ base: 24, lg: 32 }}>
        <ContactSection />
      </Row>
    </>
  );
};

export default Homepage;

export const getStaticProps: GetStaticProps = async ({ locale = 'en' }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'home'])),
    },
  };
};
