import React from 'react';
import type { NextPage } from 'next';
import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import HomeHero from 'components/blocks/HomeHero';
import SectionTitle from 'components/blocks/SectionTitle';

import PostsList from 'components/posts/PostsList';
import useTranslation from 'hooks/useTranslation';
import { Box } from '@chakra-ui/react';
import theme, { containerProps } from 'styles/theme';

const HomePage: NextPage = () => {
  const { t } = useTranslation('home');

  return (
    <>
      <Head>
        <title>Mehdi Amrane | Fullstack JavaScript Developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box bgColor='white' mb={20} mt={16} w='full' as='main'>
        <Box
          bgImage={`linear-gradient(to bottom, ${theme.colors.white}, ${theme.colors.gray[200]})`}
          borderBottom='2px solid'
          borderColor='gray.300'
        >
          <HomeHero />
        </Box>

        <Box {...containerProps}>
          <SectionTitle
            title={t('section.posts.title')}
            subtitle={t('section.posts.subtitle')}
            moreHref='/blog'
          />
          <PostsList />
        </Box>

        <Box {...containerProps}>
          <SectionTitle
            title={t('section.snippets.title')}
            subtitle={t('section.snippets.subtitle')}
            moreHref='/snippets'
          />
          <PostsList />
        </Box>

        <Box {...containerProps} pb={{ base: 16, md: 20 }}>
          <SectionTitle
            title={t('section.projects.title')}
            subtitle={t('section.projects.subtitle')}
            moreHref='/projects'
          />
          <PostsList />
        </Box>
      </Box>
    </>
  );
};

export default HomePage;

export const getStaticProps: GetStaticProps = async ({ locale = 'en' }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'home'])),
    },
  };
};
